// import 'package:get/get.dart';

import 'package:get/get_navigation/src/root/internacionalization.dart';

class MyTranslation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "lang": "اختر اللغة",
          "vent": "فضفض",
          "edit_account": "تعديل الحساب",
          "share_app": "مشاركة التطبيق",
          "privacy_policy": "سياسة الخصوصية",
          "terms_and_conditions": "الشروط والأحكام",
          "logout": "تسجيل الخروج",
          "delete_account": "حذف الحساب",
          "name": "الاسم",
          "country": "الدولة",
          "save_changes": "حفظ التغييرات",
          "home": "البيت",
          "account": "الحساب",
          "login_with_google": "المتابعة بواسطة حساب جوجل",
          "login_with_facebook": "المتابعة بواسطة حساب فيسبوك",
          "best_community":
              "المجتمع الأفضل للتحدث مع أشخاص عشوائيين بسرعة وسرية تامة",
          "welcome": "أهلاً وسهلاً",
          "delete_account_message":
              "سيتم حذف حسابك نهائياً من قاعدة البيانات الخاصة بنا",
          "delete_account_confirmation": "هل أنت متأكد من حذف الحساب؟",
          "cancel": "تراجع",
          "delete_account_warning":
              "سيتم حذف حسابك نهائياً من قاعدة البيانات الخاصة بنا في خلال 30 يومًا من الآن، ويمكنك الدخول إليه في هذه الفترة.",
          "status": "الحالة",
          "yes": "نعم",
          "change": "تغيير",
          "search": "البحث",
          "doexist": "هل تريد الخروج من التطبيق",
          "male": "ذكر",
          "female": "أنثى",
          "all": "الكل",
          "delete": "حذف",
          "friends": "الاصدقاء",
          "user_added": 'تم اضافة المستخدم بنجاح',
          "user_deleted": 'تم حذف المستخدم بنجاح',
          "agree_privacy_policy": 'أوافق على شروط الخدمة وسياسة الخصوصية',
          "agree": "اوافق",
          "refuse": "رفض",
          "edit_profile_succss": "تم تحديث بيانات الحساب بنجاح",
          "no_users_found": "لا يوجد مستخدمين متوفرين الان",
          "try_again": "ارجوك حاول في وقت لاحق",
          "worldwide": "جميع العالم",
          "image_sent": "صوره",
          "search_for_best_match": "البحث عن أفضل تطابق لك",
          "bypass": "تجاوز",
          "correspondence": "مراسله",
          "gender": "النوع",
          "your_friends": "اصدقاؤك",
          "friendship_requests": "طلبات الصداقه",
          "write_massge": "اكتب رسالتك",
          "users": "المستخدمين",
          "user": "المستخدم",
          "audio_sent": "رساله صوتيه",
          "chat_request": "تم ارسال طلب محادثه",
          "currency": "عملة",
          "currencies": "عملات",
          "your_currencies": "عملاتك",
          "getting_currencies": "الحصول على عملات",
          "age": "العمر",
          "write_your_age": "اكتب عمرك",
          "watching_ads": "مشاهدة الإعلان",
          "you_have_won": "لقد ربحت ",
          "you_got": "لقد حصلت ",
          "show_ad_before_loaded": "تحذير: محاولة إظهار الاعلان قبل التحميل",
          "ad_loaded": "يتم تحميل الاعلان ",
          "something_wrong": "يوجد خطاء ما",
          "quantity": "الكميه ",
          "delete_conversation": "هل تريد حذف المحادثه ",
          "close": "غلق",
          "send": "ارسال",
          "photo_shoot": "التقاط صوره",
          "choose_picture": "اختيار صوره",
        },
        "en": {
          "close": "close",
          "send": "send",
          "photo_shoot": "photo shoot",
          "choose_picture": "choose picture",
          "delete_conversation": "Do you want to delete the conversation",
          "you_have_won": "You have won",
          "you_got": "you got",
          "show_ad_before_loaded": "Warning: attempt to show ad before loaded",
          "ad_loaded": "The ad is being loaded",
          "something_wrong": "Something went wrong",
          "quantity": "Quantity",
          "your_currencies": "Your currencies",
          "currency": "Currency",
          "currencies": "Currencies",
          "getting_currencies": "Getting Currencies",
          "age": "Age",
          "write_your_age": "Write your age",
          "watching_ads": "Watching ads",
          "your_friends": "Your friends",
          "friendship_requests": "Friendship Requests",
          "write_massge": "write your message",
          "audio_sent": "voice message",
          "chat_request": "A chat request has been sent.",
          "bypass": "bypass",
          "correspondence": "correspondence",
          "gender": "gender",
          "users": "users",
          "user": "user",
          "image_sent": "image",
          "edit_profile_succss": "Account information updated successfully",
          "delete": "delete",
          "friends": "Friends",
          "user_added": 'User added successfully',
          'user_deleted': 'User deleted successfully',
          "no_users_found": "No users found",
          "try_again": "Please try again later.",
          "agree_privacy_policy.":
              "I agree to the terms of service and privacy policy.",
          "agree": "Agree",
          "refuse": "Refuse",
          "male": "Male",
          "female": "Female",
          "all": "All",
          "worldwide": "Worldwide",
          "search_for_best_match": "Search for the best match for you",
          "lang": "Choose Language",
          "yes": "yes",
          "doexist": 'Do you want to exit the app?',
          "vent": "Vent",
          "edit_account": "Edit Account",
          "share_app": "Share App",
          "privacy_policy": "Privacy Policy",
          "terms_and_conditions": "Terms and Conditions",
          "logout": "Logout",
          "delete_account": "Delete Account",
          "name": "Name",
          "country": "Country",
          "save_changes": "Save Changes",
          "home": "Home",
          "account": "Account",
          "login_with_google": "Login with Google",
          "login_with_facebook": "Login with Facebook",
          "best_community":
              "The best community to chat with random people quickly and with complete privacy",
          "welcome": "Welcome",
          "delete_account_message":
              "Your account will be permanently deleted from our database",
          "delete_account_confirmation":
              "Are you sure you want to delete your account?",
          "cancel": "Cancel",
          "delete_account_warning":
              "Your account will be permanently deleted from our database within 30 days from now, and you can access it during this time.",
          "status": "Status",
          "change": "Change",
          "search": "Search"
        }
      };
}
